---
- name: Playbook que crea un nuevo proyecto
  become: true
  hosts: all
  tasks:
    - name: Create a project using apply
      community.okd.k8s:
        state: present
        resource_definition:
          apiVersion: project.openshift.io/v1
          kind: Project
          metadata:
            name: testing
