---
- name: Playbook que despliega Wordpress
  become: true
  hosts: all
  tasks:
    - name: Apply file
      shell: "oc apply -f https://raw.githubusercontent.com/jtorres432/openshift-demo-app/refs/heads/main/mysql.yml"
