---
- name: Playbook que despliega el operador de Dynatrace en Openshift
  become: true
  hosts: all
  tasks:
    - name: Descarga HELM en bastion
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4
        dest: /var/tmp/get_helm.sh
        mode: '0777'
    - name: cambia owner
      shell: "chown lab-user:users /tmp/get_helm.sh"
    - name: Instala HELM en bastion
      shell: "sh /tmp/get_helm.sh"
      ignore_errors: True
    - name: Despliega el operador
      shell: "/usr/local/bin/helm install dynatrace-operator oci://public.ecr.aws/dynatrace/dynatrace-operator --create-namespace --namespace dynatrace --rollback-on-failure --force-conflicts"
#      kubernetes.core.helm:
#        name: dynatrace-operator
#        chart_ref: oci://public.ecr.aws/dynatrace/dynatrace-operator
#        release_namespace: dynatrace
#        create_namespace: true
    - name: Despliega el dynakube
      shell: "oc apply -f https://github.com/jtorres432/openshift-demo-app/blob/main/dynakube.yml"
